name: 'Setup Pkl'
description: 'Setup Pkl by installing, downloading, and adding it to the path.'
author: 'Pkl Community'

branding:
  icon: 'star'
  color: 'green'

inputs:
  pkl-version:
    description: The Pkl version to install.
    required: true

runs:
  using: 'node20'
  main: 'dist/index.js'
